---
- hosts: all
  tasks:
    - name: cleaning files
      shell: sudo rm -rf ~/SPM

    - name: pull
      shell: sudo git clone https://github.com/manan-goradiya-itp/SPM.git
      
    - name: docker kill
      shell: sudo docker stop ansapp || true && sudo docker rm ansapp || true
    
    - name: docker build
      shell: sudo docker build -t spm2605/ansapp ~/SPM/
      
    - name: docker run 
      shell:  sudo docker run -it -d --name ansapp -p 3100:80 spm2605/ansapp
